seo: 
  site_name: Julita Creations Studio
  title: Julita Creations | Web Design & Development - Food and Restaurant Photography in Milan, Italy
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url: