seo: 
  site_name: Julita Creations Studio
  title: Julita Creations | Web Design & Development - Food and Restaurant Photography in Milan, Italy
  description: One-person Web Design & Development and Photography studio specialising in Food, Beverage & Service-based businesses that care about the details.
  keywords: 
  social_image: /images/jcs-profile-image.jpg
  author: 
  favicon_image: 
social: 
  instagram_username: julitacreations.studio
  facebook_url: